#!/bin/bash

#  Marmoset: a student project snapshot, submission, testing and code review
#  system developed by the Univ. of Maryland, College Park
#
#  Developed as part of Jaime Spacco's Ph.D. thesis work, continuing effort led
#  by William Pugh. See http://marmoset.cs.umd.edu/
#
#  Copyright 2005 - 2011, Univ. of Maryland
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

function usage() {
    echo "Usage: $0 [ <database data dir> ] "
    exit
}

case $1 in 
    -h | -help | --help )
	usage;;
esac


if [ "$1" != "" ]; then
    DIR=$1
else
    DIR=$HOME/submitServerDatabase
fi

echo "Shutting down database at $DIR"

$MYSQL_HOME/bin/mysqladmin \
--socket=$DIR/submitserver.sock \
shutdown
